import Head from 'next/head'
import styles from '../styles/utils.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.heading2Xl}>
        Welcome to Italian Startups .com!
      </h1>
      <p>pls help</p>
   </div>
  )};